### ISSUE TITLE
iOS / Android safearea

### ISSUE THREAD

**Issue by mars3142** [japalekhin/langaw#2]
What will be the best practice to move the MusicButton, SoundButton and ScoreDisplay within the safe area? The same is needed at the bottom of the screen. Does flame supports a safe area? It's needed for iPhone X/Xs and newer Android phones, with a notch/cutout.

**Comment by japalekhin** [comment]
@mars3142 heyi sorry, i know this is almost a year old. but flame is just another widget (via `gameInstance.widget`) so you just wrap that with a `SafeArea` and it should work.
